version: '3'

services:
  loansapi:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: loans-docker
    container_name: loansapi
    restart: always 
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}

  db:
    image: mongo:5
    container_name: mongo-loans
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: loans
    volumes:
      - ./data/db:/data/db
