// Generated by https://quicktype.io

export interface LoanResponse {
    id:          number;
    bank:        string;
    title:       string;
    valid:       boolean;
    amount:      number;
    months:      number;
    interest:    number;
    description: string;
}
